# Generated by Django 4.2.5 on 2023-09-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='heading',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
