# Generated by Django 4.2.7 on 2023-11-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepagegalleryimage_caption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageGalleryImage',
        ),
    ]
