# Generated by Django 4.2.7 on 2024-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage_description_contactpage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
