# Generated by Django 4.2.7 on 2024-02-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('contact', '0003_contactpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
