# Generated by Django 4.2.7 on 2023-12-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchedulePage',
            new_name='SchduleIndexPage',
        ),
    ]
