# Generated by Django 4.2.7 on 2023-12-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('schedule', '0003_schedulepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchduleIndexPage',
            new_name='ScheduleIndexPage',
        ),
    ]
