# Generated by Django 4.2.7 on 2024-01-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_schduleindexpage_scheduleindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulePage',
        ),
    ]
